"""
backend/app/db/__init__.py

Feature 25: Database design, canonical collection constants, storage schemas,
MongoDB $jsonSchema validators, and index specifications.
"""

from app.db.collections import (
    ALL_COLLECTIONS,
    ANALYTICS_COLLECTIONS,
    APPEND_ONLY_COLLECTIONS,
    EXISTING_COLLECTIONS,
    WEEKLY_COLLECTIONS,
)
from app.db.indexes import COLLECTION_INDEXES
from app.db.storage_models import (
    ActivityEventStorage,
    AffectiveWeeklyStorage,
    AssignmentStorage,
    AttendanceStorage,
    AuditLogStorage,
    BehaviorWeeklyStorage,
    ConsentNoticeStorage,
    ConsentRecordStorage,
    CourseStorage,
    CourseWeekStorage,
    EngagementTrajectoryStorage,
    EnrolmentStorage,
    GradeStorage,
    IdentityVaultStorage,
    IngestionRunStorage,
    InterventionOutcomeStorage,
    InterventionRecommendationStorage,
    InterventionStorage,
    QuizAttemptStorage,
    QuizStorage,
    RecommendationStorage,
    RiskAssessmentStorage,
    SchemaMigrationStorage,
    StorageDocument,
    SubmissionStorage,
    TextMessageStorage,
    UserStorage,
    WeeklyStorageDocument,
)
from app.db.validators import (
    COLLECTION_STORAGE_MODELS,
    COLLECTION_VALIDATORS,
    generate_mongo_schema,
)

__all__ = [
    "ALL_COLLECTIONS",
    "ANALYTICS_COLLECTIONS",
    "APPEND_ONLY_COLLECTIONS",
    "ActivityEventStorage",
    "AffectiveWeeklyStorage",
    "AssignmentStorage",
    "AttendanceStorage",
    "AuditLogStorage",
    "BehaviorWeeklyStorage",
    "COLLECTION_INDEXES",
    "COLLECTION_STORAGE_MODELS",
    "COLLECTION_VALIDATORS",
    "ConsentNoticeStorage",
    "ConsentRecordStorage",
    "CourseStorage",
    "CourseWeekStorage",
    "EXISTING_COLLECTIONS",
    "EngagementTrajectoryStorage",
    "EnrolmentStorage",
    "GradeStorage",
    "IdentityVaultStorage",
    "IngestionRunStorage",
    "InterventionOutcomeStorage",
    "InterventionRecommendationStorage",
    "InterventionStorage",
    "QuizAttemptStorage",
    "QuizStorage",
    "RecommendationStorage",
    "RiskAssessmentStorage",
    "SchemaMigrationStorage",
    "StorageDocument",
    "SubmissionStorage",
    "TextMessageStorage",
    "UserStorage",
    "WEEKLY_COLLECTIONS",
    "WeeklyStorageDocument",
    "generate_mongo_schema",
]
