"""add_profiles_table

Revision ID: 7a1be437c3bf
Revises: 92bb73e0c10b
Create Date: 2026-10-08 03:37:50.305333
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1be437c3bf'
down_revision: Union[str, None] = '92bb73e0c10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
