"""add_profiles_table

Revision ID: 92bb73e0c10b
Revises: f0e0c3230b98
Create Date: 2026-10-08 03:36:22.055447
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bb73e0c10b'
down_revision: Union[str, None] = 'f0e0c3230b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=100), nullable=True, comment='Institutional student registration / matriculation number.'),
    sa.Column('department', sa.String(length=255), nullable=True, comment='Faculty or department name.'),
    sa.Column('bio', sa.Text(), nullable=True, comment='Short self-description written by the user.'),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True, comment="Absolute URL to the user's avatar image."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_student_id'), 'profiles', ['student_id'], unique=True)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_student_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
